### ISSUE TITLE
TheRole, установка и изучение

### ISSUE THREAD

**Issue by the-teacher** [sedx/the-role-issues#1]
гем TheRole поставляется в виде Rails Engine, что означает, что гем повторяет структуру рельсового приложения.

В начале работы над гемом предлагаю
1. скачать TheRole на локальную машину.
2. скачать на локальную машину зависимый гем https://github.com/TheProfitCMS/the_role_bootstrap3_ui
3. в основном геме найти DummyApp (смотри документацию)
4. запустить тесты и убедиться что все они работают или не работают. Т.е. выяснить текущее положение дел

-- все шаги по выполнению задачи конспектировать в текущем тикете
-- все трудности, вопросы, неточности в документации фиксировать тоже здесь
-- после выясения обстоятельств - будем решать какие дальнейшие шаги предпринять

**Comment by sedx** [comment]
### Запуск Dummy
- При открытии root_path получаем ошибку `couldn't find file 'bootstrap' with type 'text/css'` связано это скорее всего с тем что изменился синтаксис подключения `bootstrap-sass` тепрь вместо `//require bootstrap` используется:

```
@import "bootstrap-sprockets";
@import "bootstrap";
```
- `the_role_bootstrap3_ui` использует не определенные в `the_role` роуты:
  - `export_admin_roles_path`
  - `import_admin_roles_path`
  - `role_export_admin_role_path`

### Результаты запуска тестов

25 тестов упало.
Часть из-за отсутствия HTTP_REFERER
Также много упавших тестов которые используется методы вызывающие `.to_hash`. Происходит это потому, что `.to_hash` берет поле `the_role`, в которое пишется хэш как строка и `JSON.parse(the_role)` валится, возвращая `{}`.
Есть предложение использовать `serialize :the_role, Hash` тогда в базе будет храниться разрешения в YAML формате, и при каждом обращении к роли будет возврщаться хэш, а не строка. Заодно это сократит и ускорит код. (скорее всего можно будет полностью отказаться от преобразрвания в JSON)

### Вопросы
1. Имеет ли смысл тащить за собой гемы 'pg', 'mysql2' если dummy испоьзует только sqlite?
2. После создания пользователя по умолчанию, если в конфигурации не указано, ему не присваивается ни каких ролей, по этому в dummy после регистрациии получаю: `undefined method 'name' for nil:NilClass`
   может имеет смысл сделать так, чтo если у пользователя нет роли то ему присваивается роль по умолчанию например `user_without_rights`. реализовать можно либо чер хук `before_save` либо переопределением метода `.role` класса `User` например так 

```
def role
  if super.nil?
    ::Role.new({
      name:'user_without_rights',
      title:'User whithout rights',
      description:'User without rights'})
  else
    super
  end
end
```

И такому пользователю выдавать права только на просмотр.

**Comment by the-teacher** [comment]
**Планы**

Следующий релиз необходимо переработать
1. TheRole разделится на 3 разных проекта DummyApp, TheRoleApi и TheRoleBootstrapUI
2. TheRole - станет фактически пустым  гемом, который будет только лишь тянуть за собой через зависимости TheRoleAPI и TheRoleBootstrapUI. При необходимости пользователь сможет устанавливать только TheRoleAPI

следовательно тебе предстоит разобраться в rals engine и самостоятельно подготовить довольно большйо релиз. Хотя сложной работы в нем не будет, но ты сможешь познакомиться с устройством рельсовых проектов, базирующихся на engines

**По пунктам**

> При открытии root_path получаем ошибку couldn't find file 'bootstrap' with type 'text/css'
> Будем считать это твоей первой задачей. Ожидаю твоих правок. Сможешь сам исправить и оформить пулл реквест?
> 
> the_role_bootstrap3_ui использует не определенные в the_role роуты: 

надо поставить the_role из мастера
судя по коду роуты должны работать https://github.com/the-teacher/the_role/blob/master/config/routes.rb#L6

попробуй. сообщи о результатах

> Имеет ли смысл тащить за собой гемы 'pg', 'mysql2' если dummy испоьзует только sqlite?
> мне легко переключить адаптер в конфиге и запустить тесты под другой БД. да, наверное имеет
> 
> После создания пользователя по умолчанию, если в конфигурации не указано, ему не присваивается ни каких ролей, по этому в dummy после регистрациии получаю: undefined method 'name' for nil:NilClass

Вообще создание пользователя буз какой либо роли на мой взгляд не очень правильно. Я ожидаю, что роль по-умолчанию, которая указана в конфиге должна существовать до момента создания пользователя. Если это не так, надо понять почему

создавать роль при неудачной попытке проверки прав -не хорошо. С какой стати проверка должна инициализировать создание чего-то?

Считаю задачу закрытой.

Выделяю в отдельные тикеты.
