### ISSUE TITLE
Упавшие тесты из-за отсутствия HTTP_REFERER

### ISSUE THREAD

**Issue by the-teacher** [sedx/the-role-issues#4]
Довольно странно, ведь раньше они работали. Если тесты падают именно из-за этого нужно найти причину и устранить ее.

Следовательно, по результатам задачи получить пулл реквест

**Comment by sedx** [comment]
Проблема возникала из-за тестов упавших по причине описаной в [5 тикете](https://github.com/sedx/the-role-issues/issues/5)

После правок не наблюдается.
