### ISSUE TITLE
Много упавших тестов которые используется методы вызывающие .to_hash

### ISSUE THREAD

**Issue by the-teacher** [sedx/the-role-issues#5]
1) Однозначно правила доступа будут хранится в JSON формате в виде строки
2) serialize варианты расходятся с концептом

`.to_hash` не совсем понятно что происходит с ним. Предлагаю постаивть в DummyApp версию TheRole из мастера

**Comment by sedx** [comment]
я мастер вытягивал.
сейчас в бд разрешения (поле `the_role` в бд) хрянятся как хэш преобразованый в строку ("{:pages=>{:index=>true, :show=>true, :new=>true, :create=>true, :edit=>true, :update=>true, :destroy=>true, :my=>true, :secret=>false}}")

поэтому их парсинг `JSON.load(the_role)` возвращает исключение, так как строка не является валидным JSONом.

просто при сохранении записи разрешения преобразовываются в JSON только в том случае если разрешения пустые или являются экземпляром класса Hash

```
rules_set     = self.the_role
self.the_role = {}.to_json        if rules_set.blank?
self.the_role = rules_set.to_json if rules_set.is_a?(Hash)
```

Но например вот этот кусок кода из `seeds.rb`

```
Role.create!(
  name: :pages_moderator,
  title: :pages_moderator,
  description: :can_do_anything_with_pages,
  the_role: { moderator: { pages: true } }
)
```

записывает в `the_role` строку  `"{:moderator=>{:pages=>true}}"`

и вобще судя по методу:

```
 def _jsonable role
      return role if role.is_a? String
      role.to_json
    end
```

который вызывается перед обновлением и созданием роли предполагается что роль или строка или хэш. 

Может придти к единому формату? Например в базе только JSON как только обращаемся к полю `the_role` возвращаем хэш и используем только хэш, как только пишем в базу `the_role` сразу же форматируем его в JSON в хуке before_save без предварительного перевода в JSON

**Comment by sedx** [comment]
Если такой формат хранения в БД усторит `"{\"pages\":{\"index\":true,\"show\":true,\"new\":true,\"create\":true,\"edit\":true,\"update\":true,\"destroy\":true,\"my\":true,\"secret\":false}}"` то можно все таки использовать `serialize :the_role, JSON`
Одна строчка исправляет все тесты.
Результат `serialize :the_role, JSON` такой же как и у`self.the_role = the_role.to_json`

**Comment by the-teacher** [comment]
нет не устроит
в Бд должен ыть JSON
то что имеем - это ruby пердставление
хрень какая то

**Comment by sedx** [comment]
Направил pull request
Теперь в базе хранится чистый валидный JSON
Сделал так, что при присвоении значения атрибуту the_role, значение сразу преобразуется в JSON. При обращении к атрибуту JSON преобразуется обратно в хэш.

Все тесты кроме трех стали проходить. Падают те в которых @role.the_role ожидают строку.

**Comment by the-teacher** [comment]
Все тесты зеленые
